name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  validate:
    name: Pre-publish Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run typecheck

      - name: Check circular dependencies
        run: npm run check:circular

  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build Library
        run: npm run build:lib

      - name: Verify build output
        run: |
          if [ ! -d "dist-lib" ]; then
            echo "ERROR: dist-lib directory was not created"
            exit 1
          fi
          ls -la dist-lib/

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
